regions:
  - us-east-1
  - ap-south-1
aws_boto_clients:
  - ec2
  - autoscaling
services:
  - images:
      filters:
        - Name: name
          Values:
            - ansible*
        - Name: tag:env
          Values:
            - test-raghav
    service_name: first
    job_name: first
    regions:
      - us-east-1
      - ap-south-1
  - images:
      filters:
        - Name: name
          Values:
            - ansible*
        - Name: tag:env
          Values:
            - test-raghav
    service_name: second
    job_name: second
    regions:
      - us-east-1
      - ap-south-1
