regions:
  - us-east-1
  - ap-south-1
aws_boto_clients:
  - ec2
  - autoscaling
  - ssm
services:
  ServiceOne:
    Properties:
      ami_filters:
      - Name: 'tag:Name'
        Values: 
        - 'nginx-ami'
      launch_config_name: nginx-service
      asg_name: nginx-service
      instance_refresh_config:
        strategy: "Rolling"
        min_healthy_percentage: 90 
        instance_warmup: 300
      regions:
        - us-east-1
      test_jobs:
      - firstTestJob
      - secondTestJob


