regions:
  - us-east-1
  - ap-south-1
aws_boto_clients:
  - ec2
  - autoscaling
  - ssm
services:
  ServiceOne:
    Properties:
      ami_id_ssm_parameter: /qa/ami_id
      launch_config_name: test-v1
      asg_name: test-asg-instance-refresh
      instance_refresh_config:
        strategy: "Rolling"
        min_healthy_percentage: 90
        instance_warmup: 300
      regions:
        - us-east-1


